openapi: 3.1.0
info:
  title: rocd REST API
  version: 0.1.0
paths:
  /peers/self/self/endpoints:
    get:
      operationId: list_endpoints
      responses:
        '200':
          description: Response with json format data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rocd.dto.endpoint_spec.EndpointSpec'
  /peers/self/self/endpoints/{uid}:
    get:
      operationId: read_endpoint
      parameters:
      - name: uid
        in: path
        description: Get parameter `uid` from request url path.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Response with json format data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rocd.dto.endpoint_spec.EndpointSpec'
    put:
      operationId: update_endpoint
      parameters:
      - name: uid
        in: path
        description: Get parameter `uid` from request url path.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Response with json format data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rocd.dto.endpoint_spec.EndpointSpec'
components:
  schemas:
    rocd.dto.endpoint_spec.EndpointDir:
      type: string
      enum:
      - input
      - output
      - duplex
    rocd.dto.endpoint_spec.EndpointDriver:
      type: string
      enum:
      - pipewire
    rocd.dto.endpoint_spec.EndpointSpec:
      type: object
      required:
      - endpoint_uuid
      - endpoint_type
      - stream_direction
      - driver
      - display_name
      - system_name
      properties:
        display_name:
          type: string
          description: Human-readable name.
        driver:
          $ref: '#/components/schemas/rocd.dto.endpoint_spec.EndpointDriver'
        endpoint_type:
          $ref: '#/components/schemas/rocd.dto.endpoint_spec.EndpointType'
        endpoint_uuid:
          type: string
          description: Globally unique endpoint identifier.
        stream_direction:
          $ref: '#/components/schemas/rocd.dto.endpoint_spec.EndpointDir'
        system_name:
          type: string
          description: OS name (if any).
    rocd.dto.endpoint_spec.EndpointType:
      type: string
      enum:
      - system_device
      - streaming_device
