openapi: 3.1.0
info:
  title: rocd REST API
  version: 0.1.0
paths:
  /peers/self/self/ports:
    get:
      operationId: list_ports
      responses:
        '200':
          description: Response with json format data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rocd.dto.port_descriptor.PortDescriptor'
  /peers/self/self/ports/{uid}:
    get:
      operationId: read_port
      parameters:
      - name: uid
        in: path
        description: Get parameter `uid` from request url path.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Response with json format data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rocd.dto.port_descriptor.PortDescriptor'
    put:
      operationId: update_port
      parameters:
      - name: uid
        in: path
        description: Get parameter `uid` from request url path.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Response with json format data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rocd.dto.port_descriptor.PortDescriptor'
components:
  schemas:
    rocd.dto.port_descriptor.PortDescriptor:
      type: object
      required:
      - port_type
      - port_direction
      - port_driver
      - uid
      - display_name
      - system_name
      properties:
        display_name:
          type: string
        port_direction:
          $ref: '#/components/schemas/rocd.dto.port_descriptor.PortDirection'
        port_driver:
          $ref: '#/components/schemas/rocd.dto.port_descriptor.PortDriver'
        port_type:
          $ref: '#/components/schemas/rocd.dto.port_descriptor.PortType'
        system_name:
          type: string
        uid:
          type: string
    rocd.dto.port_descriptor.PortDirection:
      type: string
      enum:
      - input
      - output
      - duplex
    rocd.dto.port_descriptor.PortDriver:
      type: string
      enum:
      - pipewire
    rocd.dto.port_descriptor.PortType:
      type: string
      enum:
      - system_device
      - streaming_device
